language: php

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

php:
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - pear config-set preferred_state beta
  - yes '' | pecl install apcu
  - composer install

script:
  - vendor/bin/phpcs --standard=PSR2 -n src
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls -v
